export const CHARACTERS = {
  DUKE: 'Duke',
  ASSASSIN: 'Assassin',
  CAPTAIN: 'Captain',
  AMBASSADOR: 'Ambassador',
  CONTESSA: 'Contessa',
};

export const CHARACTER_INFO = {
  Duke: {
    color: '#7B2FBE',
    colorLight: '#9b4dca',
    bgGradient: 'linear-gradient(160deg, #1a0033 0%, #3d0080 40%, #7B2FBE 80%, #9b4dca 100%)',
    borderColor: '#B57BFF',
    glowColor: 'rgba(123,47,190,0.6)',
    symbol: '♔',
    title: 'The Duke',
    shortDesc: 'Taxes · Blocks Foreign Aid',
    description: 'Take 3 coins (Taxes). Block any Foreign Aid attempt.',
  },
  Assassin: {
    color: '#C41E3A',
    colorLight: '#e53e5e',
    bgGradient: 'linear-gradient(160deg, #2a0008 0%, #6b0018 40%, #C41E3A 80%, #e53e5e 100%)',
    borderColor: '#FF6B8A',
    glowColor: 'rgba(196,30,58,0.6)',
    symbol: '⚔',
    title: 'The Assassin',
    shortDesc: 'Assassinate (3 coins)',
    description: 'Pay 3 coins to force any player to give up an Influence card.',
  },
  Captain: {
    color: '#1565C0',
    colorLight: '#2196F3',
    bgGradient: 'linear-gradient(160deg, #000e2a 0%, #0a2860 40%, #1565C0 80%, #2196F3 100%)',
    borderColor: '#64B5F6',
    glowColor: 'rgba(21,101,192,0.6)',
    symbol: '⚓',
    title: 'The Captain',
    shortDesc: 'Steal · Blocks Stealing',
    description: 'Steal 2 coins from another player. Block stealing attempts.',
  },
  Ambassador: {
    color: '#00695C',
    colorLight: '#26A69A',
    bgGradient: 'linear-gradient(160deg, #001a16 0%, #004d40 40%, #00695C 80%, #26A69A 100%)',
    borderColor: '#80CBC4',
    glowColor: 'rgba(0,105,92,0.6)',
    symbol: '⚜',
    title: 'The Ambassador',
    shortDesc: 'Exchange · Blocks Stealing',
    description: 'Exchange Influence cards with the Court deck. Block stealing.',
  },
  Contessa: {
    color: '#AD1457',
    colorLight: '#E91E8C',
    bgGradient: 'linear-gradient(160deg, #2a0015 0%, #6b0035 40%, #AD1457 80%, #E91E8C 100%)',
    borderColor: '#F48FB1',
    glowColor: 'rgba(173,20,87,0.6)',
    symbol: '✦',
    title: 'The Contessa',
    shortDesc: 'Blocks Assassination',
    description: 'Block assassination attempts against you.',
  },
};

export const ACTIONS = {
  INCOME: 'income',
  FOREIGN_AID: 'foreign_aid',
  COUP: 'coup',
  TAXES: 'taxes',
  ASSASSINATE: 'assassinate',
  STEAL: 'steal',
  EXCHANGE: 'exchange',
};

export const ACTION_INFO = {
  income: {
    id: 'income',
    name: 'Income',
    description: 'Take 1 coin from the bank.',
    cost: 0,
    coinsGained: 1,
    requiresTarget: false,
    challengeable: false,
    blockable: false,
    requiredCharacter: null,
    blockedBy: [],
    blockableByTarget: false,
    blockableByAnyone: false,
    color: '#8B7536',
  },
  foreign_aid: {
    id: 'foreign_aid',
    name: 'Foreign Aid',
    description: 'Take 2 coins from the bank.',
    cost: 0,
    coinsGained: 2,
    requiresTarget: false,
    challengeable: false,
    blockable: true,
    requiredCharacter: null,
    blockedBy: ['Duke'],
    blockableByTarget: false,
    blockableByAnyone: true,
    color: '#8B7536',
  },
  coup: {
    id: 'coup',
    name: 'Coup',
    description: 'Pay 7 coins to force a player to give up an Influence card. Cannot be blocked or challenged.',
    cost: 7,
    requiresTarget: true,
    challengeable: false,
    blockable: false,
    requiredCharacter: null,
    blockedBy: [],
    blockableByTarget: false,
    blockableByAnyone: false,
    color: '#8B0000',
  },
  taxes: {
    id: 'taxes',
    name: 'Taxes',
    description: 'Claim the Duke — take 3 coins from the bank.',
    cost: 0,
    coinsGained: 3,
    requiresTarget: false,
    challengeable: true,
    blockable: false,
    requiredCharacter: 'Duke',
    blockedBy: [],
    blockableByTarget: false,
    blockableByAnyone: false,
    color: '#7B2FBE',
  },
  assassinate: {
    id: 'assassinate',
    name: 'Assassinate',
    description: 'Claim the Assassin — pay 3 coins to force a player to give up an Influence card.',
    cost: 3,
    requiresTarget: true,
    challengeable: true,
    blockable: true,
    requiredCharacter: 'Assassin',
    blockedBy: ['Contessa'],
    blockableByTarget: true,
    blockableByAnyone: false,
    color: '#C41E3A',
  },
  steal: {
    id: 'steal',
    name: 'Steal',
    description: 'Claim the Captain — take up to 2 coins from another player.',
    cost: 0,
    requiresTarget: true,
    challengeable: true,
    blockable: true,
    requiredCharacter: 'Captain',
    blockedBy: ['Captain', 'Ambassador'],
    blockableByTarget: true,
    blockableByAnyone: false,
    color: '#1565C0',
  },
  exchange: {
    id: 'exchange',
    name: 'Exchange',
    description: 'Claim the Ambassador — exchange Influence cards with the Court deck.',
    cost: 0,
    requiresTarget: false,
    challengeable: true,
    blockable: false,
    requiredCharacter: 'Ambassador',
    blockedBy: [],
    blockableByTarget: false,
    blockableByAnyone: false,
    color: '#00695C',
  },
};

export const TURN_PHASES = {
  ACTION: 'action',
  TARGETING: 'targeting',
  RESPONSE: 'response',
  BLOCK_RESPONSE: 'block_response',
  REVEAL_FOR_CHALLENGE: 'reveal_for_challenge',
  LOSE_INFLUENCE: 'lose_influence',
  EXCHANGE_SELECT: 'exchange_select',
  PASS_DEVICE: 'pass_device',
  GAME_OVER: 'game_over',
};
